name: Migrate
on:
  workflow_run:
    workflows:
      - Perform checks
    branches:
      - main
    types:
      - completed

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Apply all pending migrations to the database
        run: pnpm exec prisma migrate deploy
        env:
          POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}
          POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
